### ISSUE TITLE
SyntaxError  in @react-navigation/routers/src/TabRouter.tsx

### ISSUE THREAD

**Issue by hadnet** [react-navigation/react-navigation-4#6629]
Using @react-navigation/native 5.0.0-alpha.35 and Expo SDK 36.0.0 and expo 3.11.9

SyntaxError: /Users/jon/ReactNativeProjects/MyApp/node_modules/@react-navigation/routers/src/TabRouter.tsx: Unexpected token (36:30)

  34 | };
  35 | 
> 36 | const TYPE_ROUTE = 'route' as const;
     |                               ^
  37 | 
  38 | export const TabActions = {
  39 |   jumpTo(name: string, params?: object): TabActionType {
Failed building JavaScript bundle.

But when I delete this "as const" everything is working ok.

**Comment by yunibaek** [comment]
For anyone coming into this issue, you can alternatively upgrade your `@babel/core` dependency (latest at 7.8.4 as of writing).

`npm install @babel/core@7.8.4 --save-dev`

I didn't want to delete my `package-lock.json` since re-installing means upgrading a bunch of other modules that got out of sync with my dependency versions listed in `package.json`
